spring:
  application:
    name: trouve_ton_match_commun

  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_PORT}/ttm_commun
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

