spring:
  application:
    name: trouve_ton_match_commun
  data:
    mongodb:
      host: localhost
      port: 27017
      database: ttm

  datasource:
    url: jdbc:postgresql://db:5432/ttm_commun
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql

  output:
    ansi:
      enabled: ALWAYS

logging:
  level:
    org.springframework: DEBUG

debug: true

jwt:
  secret: "kV73kRw7TaXECmsQ9854FuWsk3r655HMDFGkV73kRw7TaXECmsQ9854FuWsk3r655HMDFG"
  expiration: 3000000


server:
  servlet:
    context-path: /api

